import { State } from "../global.slint";
import { ScrollView } from "std-widgets.slint";
import { ModuleTile } from "../components/module_tile.slint";

export component ModuleGrid inherits Rectangle {
    vertical-stretch: 1;
    horizontal-stretch: 1;
    padding: 15px;

    property <length> tile_width: 150px;
    property <length> tile_heigth: tile_width;

    property <length> total_tile_width: (self.tile_width + self.padding) * State.modules.length + self.tile_width;
    property <int> row_count: floor(self.total_tile_width / self.width);
    property <int> col_count: floor(self.width / (self.tile_width + self.padding));

    ScrollView {
        width: parent.width;
        height: parent.height;
        viewport-width: parent.width;
        viewport-height: (row_count + 1) * (parent.tile_heigth + parent.padding);

        for module[index] in State.modules: ModuleTile {
            width: root.tile_width;
            height: root.tile_heigth;
    
            x: mod(index, root.col_count) * (root.tile_width + root.padding);
            y: floor(index / root.col_count) * (root.tile_heigth + root.padding);

            module: module;

            clicked => {
                State.active-module = self.module.name;
                State.active-page = "module";
            }
        }
    }
}