import { State } from "../global.slint";
import { ScrollView } from "std-widgets.slint";

export component ModuleGrid inherits Rectangle {
    vertical-stretch: 1;
    horizontal-stretch: 1;
    padding: 5px;

    property <length> tile_width: 80px;
    property <length> tile_heigth: tile_width;

    property <length> total_tile_width: (self.tile_width + self.padding) * State.modules.length + self.tile_width;
    property <int> row_count: floor(self.total_tile_width / self.width);
    property <int> col_count: floor(self.width / (self.tile_width + self.padding));

    for module[index] in State.modules: Rectangle {
        width: parent.tile_width;
        height: parent.tile_heigth;

        background: yellow;
        x: parent.padding + mod(index, parent.col_count) * (parent.tile_width + parent.padding);
        y: parent.padding + floor(index / parent.col_count) * (parent.tile_heigth + parent.padding);

        Text {
            text: index;
            color: black;
        }
    }
}