import { State } from "../global.slint";
import { ScrollView } from "std-widgets.slint";

export component ModuleGrid inherits Rectangle {
    vertical-stretch: 1;
    horizontal-stretch: 1;
    padding: 5px;

    property <length> tile_width: 120px;
    property <length> tile_heigth: tile_width;

    property <length> total_tile_width: (self.tile_width + self.padding) * State.modules.length + self.tile_width;
    property <int> row_count: floor(self.total_tile_width / self.width);
    property <int> col_count: floor(self.width / (self.tile_width + self.padding));

    ScrollView {
        width: parent.width;
        height: parent.height;
        viewport-width: parent.width;
        viewport-height: (row_count + 1) * (parent.tile_heigth + parent.padding);

        for module[index] in State.modules: Rectangle {
            width: root.tile_width;
            height: root.tile_heigth;
    
            background: yellow;
            x: root.padding + mod(index, root.col_count) * (root.tile_width + root.padding);
            y: root.padding + floor(index / root.col_count) * (root.tile_heigth + root.padding);
    
            Text {
                text: index;
                color: black;
            }
        }
    }
}