import { Button, LineEdit } from "std-widgets.slint";

import { State } from "../global.slint";

export component SearchBar inherits Rectangle {
    in-out property active-page <=> State.active-page;

    height: 50px;
    padding: 15px;

    Rectangle {
        y: parent.padding;
        height: parent.height - 2 * parent.padding;

        x: (parent.width - parent.padding) * 0.66;
        width: parent.width - self.x - parent.padding;

        border-color: white;
        border-width: 1px;

        Text {
            x: 5px;
            text: "Search";
            color: gray;
            font-italic: true;
            font-family: "Menlo";
            horizontal-alignment: left;
            vertical-alignment: center;
        }
    }
}