import { State, Style } from "../global.slint";
import { StartPage } from "start_page.slint";
import { ModulePage } from "module_page.slint";
import { SheetPage } from "sheet_page.slint";

export component MainPage inherits Rectangle {
    vertical-stretch: 1;
    clip: false;

    Rectangle {
        background: parent.background;
        height: parent.border-radius;
        y: parent.height - parent.border-radius;
    }

    HorizontalLayout {
        padding: Style.padding.medium;
        if State.active-page == "start": StartPage {}
        if State.active-page == "module": ModulePage {}
        if State.active-page == "sheet": SheetPage { width: root.width; }
    }
}