import { State } from "../global.slint";
import { StartPage } from "start_page.slint";

export component MainPage inherits Rectangle {
    vertical-stretch: 1;
    clip: false;

    background: black;

    Rectangle {
        background: parent.background;
        height: parent.border-radius;
        y: parent.height - parent.border-radius;
    }

    HorizontalLayout {
        padding: parent.border-radius;
        if State.active-page == "start": StartPage {}
        if State.active-page == "module": Rectangle {background: pink;}
    }
}