import { State, Callbacks } from "../global.slint";
import { PageHeader } from "../components/page_header.slint";
import { SheetList } from "../containers/sheet_list.slint";

export component ModulePage inherits Rectangle {
    VerticalLayout {
        PageHeader { text: State.active-module; }
        
        HorizontalLayout {
            SheetList {}
            // todo: insert topics view
        }
    }
}
