import { SlintModule } from "../structs/module.slint";
import { ProgressBar } from "progressbar.slint";

export component ModuleTile inherits Rectangle {
    in-out property <SlintModule> module;
    callback clicked();

    border-color: white;
    border-width: 1px;

    padding: 10px;

    Text {
        text: module.name;
        color: white;
        horizontal-alignment: left;
        vertical-alignment: top;
        font-family: "Menlo";
        font-size: 20px;
        x: parent.padding;
        y: parent.padding;
        wrap: word-wrap;

        width: parent.width - 2 * parent.padding;
        height: 4 * self.font-size;
    }

    ProgressBar {
        width: parent.width * 0.66;
        x: parent.padding;
        y: (parent.height - self.height) * 0.8;
        values: parent.module.progress;
    }

    TouchArea {
        clicked => {
            root.clicked();
        }

        width: 100%;
        height: 100%;
    }
}