import { SlintModule } from "../structs/module.slint";
import { ProgressBar } from "progressbar.slint";
import { State, Callbacks, Style } from "../global.slint";

export component ModuleTile inherits Rectangle {
    in-out property <int> module-index;
    callback clicked();

    clicked => {
        Callbacks.populate_module_page(module-index);
        State.active-module-index = module-index;
        State.active-page = "module";
    }

    border-color: Style.color.primary;
    border-width: 1px;

    padding: Style.padding.medium;

    Text {
        text: State.modules[root.module-index].name;
        color: Style.color.primary;
        horizontal-alignment: left;
        vertical-alignment: top;
        font-family: "Menlo";
        font-size: 20px;
        x: parent.padding;
        y: parent.padding;
        wrap: word-wrap;

        width: parent.width - 2 * parent.padding;
        height: 4 * self.font-size;
    }

    ProgressBar {
        width: parent.width * 0.66;
        x: parent.padding;
        y: (parent.height - self.height) * 0.8;
        values: State.modules[root.module-index].progress;
    }

    TouchArea {
        clicked => {
            root.clicked();
        }

        width: 100%;
        height: 100%;
    }
}