import { SlintSheet } from "../structs/sheet.slint";
import { ProgressBar } from "progressbar.slint";
import { State, Callbacks, Style } from "../global.slint";

export component SheetEntry inherits Rectangle {
    in-out property <int> sheet_index;
    callback clicked();

    clicked => {
        Callbacks.populate_sheet_page(
            State.active-module-index,
            self.sheet_index,
        );
        State.active-sheet-index = self.sheet_index;
        State.active-page = "sheet";
    }

    border-color: Style.color.primary;
    border-width: 1px;

    padding: Style.padding.medium;

    in-out property <length> progressbar_width: 150px;

    HorizontalLayout {
        alignment: center;

        Text {
            text: State.sheets[State.active-sheet-index].name;
            color: Style.color.primary;
            horizontal-alignment: left;
            vertical-alignment: center;
            font-family: "Menlo";
            font-size: 15px;
    
            width: root.width - 2 * root.padding - root.progressbar_width;
        }
    
        ProgressBar {
            width: root.progressbar_width;
            values: State.sheets[State.active-sheet-index].progress;
            y: (parent.height - self.height) * 0.5;
        }
    }

    TouchArea {
        clicked => {
            root.clicked();
        }

        width: 100%;
        height: 100%;
    }
}