import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

import { State, Callbacks, Style } from "./global.slint";
import { SearchBar } from "./containers/search_bar.slint";
import { MainPage } from "./pages/main_page.slint";

export { State, Callbacks }

export component AppWindow inherits Window {
    min_height: 600px;
    min_width: 800px;
    Rectangle {
        background: Style.color.background;

        VerticalBox {
            spacing: 0;
            padding: 0;
            SearchBar {}
            MainPage {}
        }
    }
}
