import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

import { SearchBar } from "./containers/search_bar.slint";

import { State } from "./global.slint";

export component AppWindow inherits Window {

    Rectangle {
        height: 400px;
        width: 600px;
        background: blue;

        VerticalBox {
            spacing: 0;
            padding: 0;
            SearchBar {}
            Rectangle {
                vertical-stretch: 1;
                clip: true;

                Rectangle {
                    y: State.active-page == "start" ? 0 : State.active-page < 0 ? - self.height - 1px : parent.height + 1px;
                    background: red;
                }
                Rectangle {
                    y: State.active-page == "module" ? 0 : State.active-page < 0 ? - self.height - 1px : parent.height + 1px;
                    background: gray;
                }
            }
        }
    }
}
