import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

import { State } from "./global.slint";
import { SearchBar } from "./containers/search_bar.slint";
import { MainPage } from "./pages/main_page.slint";

export { State }

export component AppWindow inherits Window {
    min_height: 400px;
    min_width: 600px;
    Rectangle {
        background: black;

        VerticalBox {
            spacing: 0;
            padding: 0;
            SearchBar {}
            MainPage {}
        }
    }
}
