import { SlintModule } from "./structs/module.slint";
import { SlintSheet } from "./structs/sheet.slint";
import { SlintTopic } from "./structs/topic.slint";
import { SlintTask } from "./structs/task.slint";
import { Padding, Palette } from "./structs/style.slint";

export global State {
    in-out property <string> active-page: "start";
    in-out property <int> active-module-index;
    in-out property <int> active-sheet-index;
    in-out property <int> active-task-index;

    in-out property <[SlintModule]> modules; // modules displayed on the start page
    in-out property <[SlintSheet]> sheets; // sheets displayed on the last loaded module page
    in-out property <[SlintSheet]> topics; // topics displayed on the last loaded module page
    in-out property <[SlintTask]> tasks; // tasks displayed on the last loaded sheet page
}

export global Callbacks {
    callback populate_module_page(int);
    callback populate_sheet_page(int, int);
    callback add_attempt();
    callback add_task(int);
    callback edit_task_name(string);
}

export global Style {
    in-out property <Padding> padding: {
        large: 15px,
        medium: 10px,
        small: 5px
    };
    in-out property <Palette> color: {
        background: #000000,
        primary: #FFFFFF,
        secondary: #888888
    };
}