import { SlintModule } from "./structs/module.slint";
import { SlintSheet } from "./structs/sheet.slint";
import { SlintTopic } from "./structs/topic.slint";
import { Padding } from "./structs/style.slint";

export global State {
    in-out property <string> active-page: "start";
    in-out property <string> active-module;

    in-out property <[SlintModule]> modules; // modules displayed on the start page
    in-out property <[SlintSheet]> sheets; // sheets displayed on the last loaded module page
    in-out property <[SlintSheet]> topics; // topics displayed on the last loaded module page
}

export global Events {
    callback populate_module_page(string);
}


export global Style {
    in-out property <Padding> padding: { large: 15px, medium: 10px, small: 5px };
}